### ISSUE TITLE
Effect sizes

### ISSUE THREAD

**Issue by CorentinWicht** [stamats/MKinfer#2]
Dear Prof. Kohl,

I was wondering whether it is possible to generate effect size estimates using the perm.t.test function? 

Best wishes,

Corentin Wicht

**Comment by stamats** [comment]
Dear Corentin,

indeed a good question. 

Since permutation tests are a way of determining the distribution of the test statistic under the null hypothesis and the p value is obtained by comparing the values of the test statistic of the permuted data with the original data, I would say that one could report the standard effect size estimates in this case. 

Do you know any literature suggesting a different approach? If yes, I would of course be willing to implement this in my function (as default or as an option).

Best wishes,
Matthias

**Comment by CorentinWicht** [comment]
Dear Matthias,

Many thanks for your reply. 

I would also agree with reporting the standard effect size estimates but it seems that the litterature on the topic is rather scarce (and my knowledge and understanding is limited too):
[https://akjournals.com/view/journals/168/19/1/article-p77.xml](https://akjournals.com/view/journals/168/19/1/article-p77.xml)
[https://www.researchgate.net/post/What_are_some_appropriate_types_of_effect_size_estimates_for_permutation_anova_ancova](https://www.researchgate.net/post/What_are_some_appropriate_types_of_effect_size_estimates_for_permutation_anova_ancova)
[https://mailman.science.ru.nl/pipermail/fieldtrip/2017-September/024644.html](https://mailman.science.ru.nl/pipermail/fieldtrip/2017-September/024644.html)

Effect sizes have apparently already be implemented in other toolboxes (here Hedges' g):
[https://github.com/lrkrol/permutationTest](https://github.com/lrkrol/permutationTest)

I hope this will help you in your decision process.

Many thanks and best regards,

Corentin

**Comment by stamats** [comment]
Dear Corentin,

many thanks for the links!

I had a brief look. The last one (Matlab code) uses "effectsize = observeddifference / pooledstd", not taking any permutations into consideration. Regarding the researchgate questions, I'm not sure whether bootstrap is appropriate in this case. If you want to use bootstrap, then you can also use the bootstrapped t-test. The question on the mailing lists seems to go in a different direction. 

Hence, the article remains and seems to offer a possible solution especially if the null distribution is not normal. I will have a closer look in the next days.

Best regards,
Matthias

**Comment by CorentinWicht** [comment]
Dear Matthias,

You're welcome for the links. 

Indeed, I think the main issue is related to iterations where the null distribution is not normal (hence the proposition from the Matlab code may not be very reliable). 

I will keep investigating on my side and will let you know if I find anything else related to ES in permutation-based testing. 

Many thanks  and best wishes,

Corentin

**Comment by CorentinWicht** [comment]
Dear Matthias (@stamats),

I was wondering whether you could have a closer look at the implementation of ES in permutation-based tests? 

Best wishes,

Corentin

**Comment by stamats** [comment]
Dear Corentin,

I took quite a long time, but now I have added function p2ses for computing SES based on p values from a permutation/randomization test.

Best wishes
Matthias
